name: Run tests
on:
  push:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Expose GitHub Runtime
      uses: crazy-max/ghaction-github-runtime@v3

    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run tests (by building the builder)
      run: |
        docker buildx build \
            --output=type=docker \
            --cache-to type=gha,mode=max \
            --cache-from type=gha \
            --load \
            --progress=plain \
            --target=builder \
            .
